/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.software.coursework;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
